name: music_player_backend_storage

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      PGPORT: 9732
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "9732:9732"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio
    ports:
      - "9700:9700"
      - "9701:9701"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY_FILE: /run/secrets/minioaccess
      MINIO_SECRET_KEY_FILE: /run/secrets/miniosecret
    command: server --address ":9700" --console-address ":9701" /data
    secrets:
    - minioaccess
    - miniosecret
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
    postgres:
    pgadmin:
    minio:

secrets:
  minioaccess:
    file: minioaccess.txt
  miniosecret:
    file: miniosecret.txt
