name: music_player_backend_storage

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "9732:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "9750:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: minio/minio
    ports:
      - "9700:9000"
      - "9701:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY_FILE: /run/secrets/minioaccess
      MINIO_SECRET_KEY_FILE: /run/secrets/miniosecret
    command: server --console-address ":9001" /data
    secrets:
    - minioaccess
    - miniosecret
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
    postgres:
    pgadmin:
    minio:

secrets:
  minioaccess:
    file: minioaccess.txt
  miniosecret:
    file: miniosecret.txt
