services:
  web:
    container_name: backend
    build:
      context: ../../Src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9780:8080"