services:
  web:
    container_name: backend
    build:
      context: ../../Src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9780:9780"
    extra_hosts:
      - "host.docker.internal:host-gateway"
